"""initial migration

Revision ID: 7c0e341f924a
Revises: 5a8ca5458d7a
Create Date: 2025-12-30 23:29:19.125888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c0e341f924a'
down_revision: Union[str, Sequence[str], None] = '5a8ca5458d7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_completed', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_done')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_done', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('is_completed')

    # ### end Alembic commands ###
